//! `xtask install`, `xtask dist` and `xtask deb`: getting the Linux build off
//! the build machine and onto a user's.
//!
//! All three lay out the same three files. `install` writes them into a prefix
//! the caller names, `dist` writes them into a staging directory and rolls it
//! into a versioned `tar.gz`, and `deb` writes them under `/usr` inside a
//! package root and hands that to `dpkg-deb`. One [`lay_out`] means the three
//! can never disagree about what an installation is.
//!
//! # What is embedded and what is installed
//!
//! **Installed**: the entire on-disk footprint, three files plus one more
//! when a settings binary is supplied:
//!
//! | Path under the prefix | What it is |
//! |---|---|
//! | `bin/robco-term` | the binary |
//! | `share/applications/robco-term.desktop` | the desktop entry, `packaging/robco-term.desktop` verbatim |
//! | `share/icons/hicolor/256x256/apps/robco-term.png` | the icon, `packaging/icons/robco-term.png` verbatim |
//! | `bin/robco-settings` | the settings window, in the shape its route ships (below) |
//!
//! `robco-settings` is not built by this workspace's own `cargo build`: it
//! is a Tcl/Tk application, and it ships in the shape its destination
//! expects. The tarball carries the single-file image
//! `settings/zipfs/build-selfcontained.sh` builds (`--settings-binary`
//! names it), because a tarball promises to run on a host with nothing
//! installed; `dist` refuses to produce one without it, and `install`
//! accepts running without one (a developer install, GUI-less). The `.deb`
//! instead ships the Tcl sources under `share/robco-term/settings`, the
//! launcher at `bin/robco-settings` with its ROOT pointed there, and
//! `tcl9.0`/`tk9.0` in its `Depends`: on Debian the interpreter is the
//! distribution's to provide, the same rule `dpkg-shlibdeps` applies to
//! the C libraries.
//!
//! **Embedded**: compiled into the binary, so none of it is installed, none
//! of it is looked up at run time, and the binary does not care where it sits
//! or whether a source checkout exists:
//!
//! - the 24 bundled font faces (`include_bytes!` in `robco-term`'s
//!   `fonts::bundled`),
//! - every shader source: the CRT chain's passes (`robco-crt-render`'s
//!   `preset`), the burn-in pass (`robco-crt-burnin`), the chassis metal, LED
//!   matrix and tape-label passes (`robco-chassis`'s `shaders`), and the
//!   grid's WGSL (`robco-term`'s `render`),
//! - the CRT chain's noise texture (`allNoise512.png`),
//! - the 14 screen and 3 chassis presets, which are Rust data in
//!   `robco-config`'s `presets`, not files.
//!
//! The chain's `.slangp` preset *is* written to a file at run time, but into
//! the user's cache directory (the `preset/robco.slangp` the startup log
//! names), from the embedded sources. It is a cache, not an installed asset:
//! deleting it costs one regeneration.
//!
//! **Neither**: created under the user's own directories on first run, and
//! no business of a package: `robco-term/config.toml` under the XDG config
//! directory, the crash log, and the instance lock and socket in
//! `XDG_RUNTIME_DIR`.
//!
//! The practical consequence, and the reason [`lay_out`] is this short: the
//! installation is relocatable. `bin/robco-term` copied anywhere runs, which
//! is what makes a plain tarball a legitimate release format here rather than
//! a shortcut.
//!
//! # The placeholder icon
//!
//! `packaging/icons/robco-term.png` is a placeholder, not branding. The app
//! has no real icon yet, so this one is plain geometry drawn from
//! nothing: an amber rounded frame around a block cursor and two bars, on the
//! near-black the screen presets use. It was generated by, and can be
//! regenerated by:
//!
//! ```text
//! convert -size 256x256 xc:'#0d0b06' \
//!   -fill none -stroke '#ffb000' -strokewidth 10 \
//!   -draw 'roundrectangle 20,20 235,235 28,28' \
//!   -fill '#ffb000' -stroke none \
//!   -draw 'rectangle 62,96 86,132' \
//!   -draw 'rectangle 62,150 170,160' \
//!   -draw 'rectangle 100,96 194,106' \
//!   png32:packaging/icons/robco-term.png
//! ```
//!
//! Real branding drops in by replacing that one file at that one path, with no
//! code change: the name it installs under is the binary's basename, which is
//! the application's identity and what the desktop entry's `Icon=` names.
//! Additional sizes, when there is art worth rendering at them, go in beside
//! it and get another line in [`ICONS`].

use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;

/// The desktop entry and the icon travel inside this binary rather than being
/// read out of a checkout, for the same reason the app's own assets do: an
/// `xtask` that has to find its source tree to install is an `xtask` that
/// installs something different depending on where it is run from.
const DESKTOP_ENTRY: &str = include_str!("../../../packaging/robco-term.desktop");

/// The icons to install, as (nominal size, bytes). One entry today; the
/// placeholder's own note says what adding more looks like.
const ICONS: &[(u32, &[u8])] = &[(
    256,
    include_bytes!("../../../packaging/icons/robco-term.png"),
)];

/// The workspace manifest, parsed at run time for the product's version.
/// `include_str!` rather than a path lookup so the number travels with the
/// binary, and so cargo rebuilds `xtask` when the version changes.
const WORKSPACE_MANIFEST: &str = include_str!("../../../Cargo.toml");

/// The application's identity: the binary's basename, which is also the
/// desktop entry's basename, the icon's basename, the WM_CLASS the window
/// presents and the Debian package's name. One string, per `app::identity`.
pub const NAME: &str = "robco-term";

/// The settings window's basename, installed as `bin/robco-settings`
/// alongside `bin/robco-term` when a `--settings-binary` is supplied. It is
/// the launcher name the Tcl/Tk app carries (`settings/robco-settings`), and
/// the name `settings/zipfs/build-selfcontained.sh`'s image reports for
/// `--version`.
pub const SETTINGS_NAME: &str = "robco-settings";

/// The product's version, from `[workspace.package]` in the workspace
/// manifest. Read, never written: bumping it is a release decision that
/// happens in the manifest, and packaging only ever stamps what it finds.
pub fn version() -> Result<String> {
    let doc: toml_edit::DocumentMut = WORKSPACE_MANIFEST
        .parse()
        .context("parsing the workspace Cargo.toml")?;
    doc.get("workspace")
        .and_then(|w| w.get("package"))
        .and_then(|p| p.get("version"))
        .and_then(|v| v.as_str())
        .map(str::to_string)
        .context("no [workspace.package] version in the workspace Cargo.toml")
}

/// `<name>-<version>-linux-<arch>`, the stem a release artifact is known by.
/// The architecture is this build's, since `robco-term` drags a C++
/// dependency (simdutf, through the terminal core) and so is built natively
/// per platform rather than cross-compiled: the artifact name has to say
/// which machine it came off.
fn artifact_stem(version: &str) -> String {
    format!("{NAME}-{version}-linux-{}", std::env::consts::ARCH)
}

/// Writes the installation under `root`, which plays the part of
/// `<destdir><prefix>`. Answers the installed paths, in the order written.
///
/// This is the whole definition of "an installation": one executable and two
/// XDG data files, plus `bin/robco-settings` when `settings_binary` is given.
/// Everything else `robco-term` needs is inside its executable (see the
/// module doc); `robco-settings` is a separate Tcl/Tk image and is only
/// copied into place, never built here.
fn lay_out(root: &Path, binary: &Path, settings_binary: Option<&Path>) -> Result<Vec<PathBuf>> {
    let mut written = Vec::new();

    let bin_dir = root.join("bin");
    std::fs::create_dir_all(&bin_dir).with_context(|| format!("creating {}", bin_dir.display()))?;
    let installed_binary = bin_dir.join(NAME);
    // Remove first: copying onto a running executable is ETXTBSY, and
    // re-installing over a live install is the normal case.
    let _ = std::fs::remove_file(&installed_binary);
    std::fs::copy(binary, &installed_binary).with_context(|| {
        format!(
            "copying {} to {}",
            binary.display(),
            installed_binary.display()
        )
    })?;
    set_mode(&installed_binary, 0o755)?;
    written.push(installed_binary);

    let applications = root.join("share/applications");
    std::fs::create_dir_all(&applications)
        .with_context(|| format!("creating {}", applications.display()))?;
    let entry = applications.join(format!("{NAME}.desktop"));
    std::fs::write(&entry, DESKTOP_ENTRY)
        .with_context(|| format!("writing {}", entry.display()))?;
    set_mode(&entry, 0o644)?;
    written.push(entry);

    for (size, bytes) in ICONS {
        let dir = root.join(format!("share/icons/hicolor/{size}x{size}/apps"));
        std::fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
        let icon = dir.join(format!("{NAME}.png"));
        std::fs::write(&icon, bytes).with_context(|| format!("writing {}", icon.display()))?;
        set_mode(&icon, 0o644)?;
        written.push(icon);
    }

    if let Some(settings_binary) = settings_binary {
        let installed_settings = bin_dir.join(SETTINGS_NAME);
        // Same ETXTBSY reasoning as the main binary above.
        let _ = std::fs::remove_file(&installed_settings);
        std::fs::copy(settings_binary, &installed_settings).with_context(|| {
            format!(
                "copying {} to {}",
                settings_binary.display(),
                installed_settings.display()
            )
        })?;
        set_mode(&installed_settings, 0o755)?;
        written.push(installed_settings);
    }

    Ok(written)
}

/// The `.deb`'s shape of the settings window: the Tcl sources under
/// `share/robco-term/settings` and the launcher at `bin/robco-settings`
/// with its ROOT pointed there, leaning on the distribution's own
/// `tcl9.0`/`tk9.0` (declared in `Depends` by [`deb`]) instead of
/// bundling an interpreter.
fn lay_out_settings_scripts(root: &Path) -> Result<Vec<PathBuf>> {
    let mut written = Vec::new();
    let source = workspace_root().join("settings");
    let share = root.join("share").join(NAME).join("settings");

    for dir in ["lib", "ui"] {
        let dest = share.join(dir);
        std::fs::create_dir_all(&dest).with_context(|| format!("creating {}", dest.display()))?;
        let from = source.join(dir);
        for entry in
            std::fs::read_dir(&from).with_context(|| format!("reading {}", from.display()))?
        {
            let path = entry?.path();
            if path.extension().is_none_or(|e| e != "tcl") {
                continue;
            }
            let target = dest.join(path.file_name().expect("a read_dir entry has a name"));
            std::fs::copy(&path, &target).with_context(|| {
                format!("copying {} to {}", path.display(), target.display())
            })?;
            set_mode(&target, 0o644)?;
            written.push(target);
        }
    }

    let launcher_source = source.join(SETTINGS_NAME);
    let launcher = std::fs::read_to_string(&launcher_source)
        .with_context(|| format!("reading {}", launcher_source.display()))?;
    let patched = point_root_at(&launcher, &format!("/usr/share/{NAME}/settings"))?;
    let bin_dir = root.join("bin");
    std::fs::create_dir_all(&bin_dir).with_context(|| format!("creating {}", bin_dir.display()))?;
    let installed_launcher = bin_dir.join(SETTINGS_NAME);
    std::fs::write(&installed_launcher, patched)
        .with_context(|| format!("writing {}", installed_launcher.display()))?;
    set_mode(&installed_launcher, 0o755)?;
    written.push(installed_launcher);

    Ok(written)
}

/// The two files Debian policy wants under `usr/share/doc/<package>`: a
/// changelog (this is a native package, so `changelog.gz`, dated from
/// HEAD's commit time like the dist tarball) and a machine-readable
/// copyright file. The license text itself is not duplicated: the crate
/// declares GPL-3.0-or-later, and Debian keeps that text in
/// `/usr/share/common-licenses/GPL-3`, which is what the file points at.
fn deb_doc_files(root: &Path, version: &str) -> Result<Vec<PathBuf>> {
    let doc = root.join("share/doc").join(NAME);
    std::fs::create_dir_all(&doc).with_context(|| format!("creating {}", doc.display()))?;

    let stamp = crate::proc::capture(
        "date",
        &["-u", "-R", "-d", &format!("@{}", released_commit_timestamp()?)],
    )?;
    let changelog = doc.join("changelog");
    std::fs::write(
        &changelog,
        format!(
            "{NAME} ({version}) unstable; urgency=medium\n\n  \
             * Built from the source tree at this version.\n\n \
             -- {}  {stamp}\n",
            maintainer()
        ),
    )
    .with_context(|| format!("writing {}", changelog.display()))?;
    // -n keeps the timestamp out of the gzip header, so the same tree
    // packages to the same bytes.
    let status = Command::new("gzip")
        .args(["-9", "-n", "-f"])
        .arg(&changelog)
        .status()
        .context("spawning gzip")?;
    if !status.success() {
        bail!("gzip exited with {status}");
    }
    let changelog_gz = doc.join("changelog.gz");
    set_mode(&changelog_gz, 0o644)?;

    let copyright = doc.join("copyright");
    std::fs::write(
        &copyright,
        format!(
            "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/\n\
             Upstream-Name: {NAME}\n\
             Source: https://github.com/overseers-desk/RobCo-Terminal\n\
             \n\
             Files: *\n\
             Copyright: 2026 RobCo Terminal contributors\n\
             License: GPL-3.0-or-later\n\
            \x20This package is distributed under the terms of the GNU General\n\
            \x20Public License, version 3 or (at your option) any later version.\n\
            \x20.\n\
            \x20On Debian systems, the complete text of the GNU General Public\n\
            \x20License version 3 can be found in /usr/share/common-licenses/GPL-3.\n"
        ),
    )
    .with_context(|| format!("writing {}", copyright.display()))?;
    set_mode(&copyright, 0o644)?;

    Ok(vec![changelog_gz, copyright])
}

/// 0755 on every directory under `root`: the staging tree inherits the
/// building user's umask, and dpkg-deb archives modes as it finds them.
fn normalize_dir_modes(root: &Path) -> Result<()> {
    set_mode(root, 0o755)?;
    for entry in std::fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let path = entry?.path();
        if path.is_dir() {
            normalize_dir_modes(&path)?;
        }
    }
    Ok(())
}

/// Rewrite the launcher's `set ROOT ...` line to the installed location.
/// The launcher derives ROOT from its own path when run from a checkout;
/// installed to `bin/` away from its sources, it has to be told. Refuses a
/// launcher with no such line rather than installing one that resolves
/// nothing.
fn point_root_at(launcher: &str, root: &str) -> Result<String> {
    if !launcher.lines().any(|l| l.starts_with("set ROOT ")) {
        bail!("the {SETTINGS_NAME} launcher has no `set ROOT` line to point at {root}");
    }
    let lines: Vec<String> = launcher
        .lines()
        .map(|line| {
            if line.starts_with("set ROOT ") {
                format!("set ROOT {root}")
            } else {
                line.to_string()
            }
        })
        .collect();
    Ok(lines.join("\n") + "\n")
}

fn set_mode(path: &Path, mode: u32) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode))
            .with_context(|| format!("chmod {mode:o} {}", path.display()))?;
    }
    #[cfg(not(unix))]
    let _ = (path, mode);
    Ok(())
}

/// The binary to package: the one the caller named, or a fresh release build.
///
/// Building here rather than making the caller do it is what lets `cargo run
/// -p xtask -- install --prefix <dir>` be the whole instruction. `--binary`
/// exists so a release pipeline can package an artifact it built (and checked)
/// earlier instead of rebuilding it.
fn resolve_binary(binary: Option<PathBuf>) -> Result<PathBuf> {
    if let Some(path) = binary {
        return std::fs::canonicalize(&path)
            .with_context(|| format!("binary not found: {}", path.display()));
    }

    eprintln!("building the release binary (`cargo build --release -p robco-app`)");
    // From the workspace root, not the caller's directory: `xtask install` is
    // runnable from anywhere (everything it installs is inside it), and a
    // `cargo build` inherited from some other directory would either fail or,
    // worse, build some other workspace.
    //
    // `--message-format=json-render-diagnostics` is how the built path is
    // *asked for* rather than guessed. Where cargo puts a target directory has
    // at least four sources: `--target-dir`, `CARGO_TARGET_DIR`,
    // `build.target-dir` in any of the layered config files, and the default
    // beside the workspace manifest. Reproducing that precedence here
    // means being wrong the first time someone's config disagrees. This was not
    // hypothetical: the first version of this function assumed
    // `CARGO_TARGET_DIR` or `<workspace>/target` and failed on a host where
    // neither held. Diagnostics still render to stderr, so the build looks the
    // same to whoever is watching it.
    let output = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()))
        .args([
            "build",
            "--release",
            "-p",
            "robco-app",
            "--message-format=json-render-diagnostics",
        ])
        .current_dir(workspace_root())
        .stderr(std::process::Stdio::inherit())
        .output()
        .context("spawning cargo")?;
    if !output.status.success() {
        bail!(
            "`cargo build --release -p robco-app` exited with {}",
            output.status
        );
    }

    let built = executable_from_cargo_messages(&String::from_utf8_lossy(&output.stdout))
        .context("cargo reported no executable artifact for robco-app")?;
    std::fs::canonicalize(&built)
        .with_context(|| format!("release build did not produce {}", built.display()))
}

/// The executable path out of cargo's JSON message stream.
///
/// A full JSON parse would buy nothing here: the field is a plain string in a
/// machine-written line, and `robco-app` produces exactly one executable, so
/// the last `"executable"` that is not `null` is it. Kept as its own function
/// so it can be tested on a recorded line rather than only against a real
/// build.
fn executable_from_cargo_messages(stdout: &str) -> Option<PathBuf> {
    const KEY: &str = "\"executable\":\"";
    stdout
        .lines()
        .filter_map(|line| {
            let start = line.find(KEY)? + KEY.len();
            let rest = &line[start..];
            let end = rest.find('"')?;
            Some(PathBuf::from(&rest[..end]))
        })
        .next_back()
}

/// The workspace root, resolved from this crate's compile-time location the
/// same way [`crate::snap`] resolves its own repo-relative lookups.
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."))
}

/// `HEAD`'s own commit timestamp (seconds since the epoch), read from git
/// rather than the wall clock.
///
/// `xtask dist` stamps this onto every entry it archives (see [`dist`]), so
/// that two runs at the same commit -- the reproducibility a release
/// pipeline or a third party rebuilding the same tag wants to be able to
/// check -- produce byte-identical tarballs. Reading it from the system
/// clock instead would make every run's archive different from every other,
/// which is what a plain `tar` invocation over a freshly-staged directory
/// already does by accident: each file's mtime is "when `dist` happened to
/// stage it", not anything about the release.
fn released_commit_timestamp() -> Result<i64> {
    let output = Command::new("git")
        .arg("-C")
        .arg(workspace_root())
        .args(["log", "-1", "--format=%ct", "HEAD"])
        .output()
        .context("spawning git to read HEAD's commit timestamp")?;
    if !output.status.success() {
        bail!(
            "git log -1 --format=%ct HEAD exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8_lossy(&output.stdout)
        .trim()
        .parse::<i64>()
        .context("git log -1 --format=%ct HEAD did not print a Unix timestamp")
}

/// Runs the *installed* copy with a scrubbed environment and checks it reports
/// the version being packaged.
///
/// Two things at once, both cheap. It proves the installed file is executable
/// and starts with no source checkout, no user config and no `HOME` it has
/// ever seen: the property the whole embedded-assets design is claiming. And
/// it catches a `--binary` that is not this tree's build, which is the one way
/// a tarball can end up named for a version it does not contain.
///
/// It deliberately does not open a window: that needs a display and belongs to
/// `xtask snap`, which already does it.
fn check_installed(installed: &Path, version: &str) -> Result<()> {
    let home = tempfile::Builder::new()
        .prefix("robco-install-check.")
        .tempdir()
        .context("creating a scratch HOME for the install check")?;

    let mut command = Command::new(installed);
    command
        .arg("--version")
        .env_clear()
        // PATH so the loader's helpers resolve; nothing else is inherited, so
        // there is no XDG variable, no CARGO_*, and no pointer to a checkout.
        .env("PATH", "/usr/bin:/bin")
        .env("HOME", home.path());
    let output = command
        .output()
        .with_context(|| format!("running {} --version", installed.display()))?;

    let reported = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if !output.status.success() {
        bail!(
            "{} --version exited with {} in a clean environment",
            installed.display(),
            output.status
        );
    }
    let expected = format!("{NAME} {version}");
    if reported != expected {
        bail!("installed binary reports {reported:?}, expected {expected:?}");
    }
    println!("  checked: {reported} runs from the prefix with a clean HOME");
    Ok(())
}

pub struct InstallArgs {
    pub prefix: PathBuf,
    pub destdir: Option<PathBuf>,
    pub binary: Option<PathBuf>,
    pub settings_binary: Option<PathBuf>,
}

pub fn install(args: InstallArgs) -> Result<()> {
    let version = version()?;
    let binary = resolve_binary(args.binary)?;
    let root = staged_root(&args.prefix, args.destdir.as_deref());

    if args.settings_binary.is_none() {
        println!(
            "note: no --settings-binary given; installing {NAME} without {SETTINGS_NAME} (the settings window). Build one with settings/zipfs/build-selfcontained.sh and re-run with --settings-binary <path> to include it."
        );
    }

    let written = lay_out(&root, &binary, args.settings_binary.as_deref())?;
    println!("installed {} {version} to {}", NAME, root.display());
    for path in &written {
        println!("  {}", path.display());
    }

    check_installed(&root.join("bin").join(NAME), &version)?;

    // The desktop entry's `Exec=` is a bare name, so a prefix outside PATH
    // installs an entry that cannot launch anything. Saying so beats writing
    // an absolute path that a later move would silently break.
    let bin_dir = root.join("bin");
    let on_path = std::env::var_os("PATH")
        .map(|path| std::env::split_paths(&path).any(|dir| dir == bin_dir))
        .unwrap_or(false);
    if !on_path {
        println!(
            "note: {} is not on PATH, so the desktop entry's `Exec=robco-term` will not resolve\n      until it is (the entry names the binary rather than one prefix on purpose).",
            bin_dir.display()
        );
    }

    Ok(())
}

/// `<destdir><prefix>`, the GNU staging idiom: with no destdir the prefix is
/// the root, and with one the prefix is re-rooted under it.
fn staged_root(prefix: &Path, destdir: Option<&Path>) -> PathBuf {
    match destdir {
        None => prefix.to_path_buf(),
        Some(dest) => dest.join(prefix.strip_prefix("/").unwrap_or(prefix)),
    }
}

pub struct DistArgs {
    pub out_dir: PathBuf,
    pub binary: Option<PathBuf>,
    pub settings_binary: Option<PathBuf>,
}

/// `xtask dist`: the install layout, rolled into a versioned `tar.gz`.
///
/// The tarball's single top-level directory is the artifact stem, so it
/// unpacks into one named directory rather than over the current one, and its
/// contents are exactly what `install` writes: relocatable, because the
/// module doc's embedded/installed split leaves nothing to relocate.
///
/// `--settings-binary` is required here, not optional as it is for `install`:
/// this is what a user downloads, and an official package with no settings
/// window is a bug, not a smaller install.
pub fn dist(args: DistArgs) -> Result<()> {
    let Some(settings_binary) = args.settings_binary else {
        bail!(
            "official {NAME} packages always carry {SETTINGS_NAME}; pass --settings-binary <path>. Build one with settings/zipfs/build-selfcontained.sh."
        );
    };

    let version = version()?;
    let mtime = released_commit_timestamp()?;
    let binary = resolve_binary(args.binary)?;
    let stem = artifact_stem(&version);

    let staging = tempfile::Builder::new()
        .prefix("robco-dist.")
        .tempdir()
        .context("creating the dist staging directory")?;
    let root = staging.path().join(&stem);
    lay_out(&root, &binary, Some(&settings_binary))?;
    check_installed(&root.join("bin").join(NAME), &version)?;

    let tarball = archive(staging.path(), &stem, &args.out_dir, mtime)?;

    let bytes = std::fs::metadata(&tarball).map(|m| m.len()).unwrap_or(0);
    println!(
        "wrote {} ({:.1} MiB)",
        tarball.display(),
        bytes as f64 / (1024.0 * 1024.0)
    );
    Ok(())
}

/// Rolls `staging/<stem>` into `<out_dir>/<stem>.tar.gz`. Split out of
/// [`dist`] so the archiving step -- the part reproducibility is actually a
/// claim about -- is callable from a test without a real binary to package
/// or a `check_installed` run to satisfy.
///
/// `--sort=name`, a fixed owner and `--mtime` keep the archive from carrying
/// this machine's uid, readdir order or the moment this happened to run into
/// a release artifact: two runs at the same `mtime` produce the same bytes
/// (`dist` sources it from [`released_commit_timestamp`], not the clock).
/// GNU tar's own flags rather than a Rust tar crate, for the reason `proc`
/// already states: the battle-tested tool is the better trade.
fn archive(staging: &Path, stem: &str, out_dir: &Path, mtime: i64) -> Result<PathBuf> {
    std::fs::create_dir_all(out_dir).with_context(|| format!("creating {}", out_dir.display()))?;
    let out_dir = std::fs::canonicalize(out_dir)
        .with_context(|| format!("resolving {}", out_dir.display()))?;
    let tarball = out_dir.join(format!("{stem}.tar.gz"));

    let status = Command::new("tar")
        .arg("--create")
        .arg("--gzip")
        .arg("--sort=name")
        .arg("--owner=0")
        .arg("--group=0")
        .arg("--numeric-owner")
        .arg(format!("--mtime=@{mtime}"))
        .arg("--file")
        .arg(&tarball)
        .arg("--directory")
        .arg(staging)
        .arg(stem)
        .status()
        .context("spawning tar")?;
    if !status.success() {
        bail!("tar exited with {status}");
    }
    Ok(tarball)
}

pub struct DebArgs {
    pub out_dir: PathBuf,
    pub binary: Option<PathBuf>,
}

/// `xtask deb`: a binary Debian package, built without root.
///
/// This is the one package format that needed no tooling this machine did not
/// already have and no privilege it did not already have: `dpkg-deb
/// --root-owner-group` writes the ownership a package needs without `fakeroot`
/// or `sudo`, and `dpkg-shlibdeps` derives the real `Depends` from the built
/// binary rather than from a list someone maintains by hand.
///
/// It is a *binary* package built from the install layout, not a Debian source
/// package: there is no `debian/rules`, no debhelper, and no build on the
/// packaging machine. The `debian/control` this writes into its scratch
/// directory exists only because `dpkg-shlibdeps` refuses to run without one.
///
/// What that costs, stated rather than hidden: the dependency versions
/// `dpkg-shlibdeps` computes are the ones on *this* machine's libraries, so a
/// package built on a newer distribution declares bounds an older one cannot
/// satisfy. That is the normal property of a locally built binary package and
/// the reason distributions build in a clean chroot; naming it is the honest
/// alternative to pretending the artifact is portable across releases.
pub fn deb(args: DebArgs) -> Result<()> {
    for tool in ["dpkg-deb", "dpkg-shlibdeps", "dpkg", "strip", "gzip", "date"] {
        if which(tool).is_none() {
            bail!("`{tool}` is not on PATH; `xtask deb` needs dpkg-dev, dpkg, binutils and coreutils");
        }
    }
    let version = version()?;
    let binary = resolve_binary(args.binary)?;
    let arch = crate::proc::capture("dpkg", &["--print-architecture"])?;

    let scratch = tempfile::Builder::new()
        .prefix("robco-deb.")
        .tempdir()
        .context("creating the deb staging directory")?;

    // dpkg-shlibdeps insists on being run from a directory holding
    // `debian/control`, and on the binary living under the package's own
    // staging path, so the layout below is its shape, not a choice.
    let debian = scratch.path().join("debian");
    std::fs::create_dir_all(&debian)?;
    std::fs::write(
        debian.join("control"),
        format!("Source: {NAME}\n\nPackage: {NAME}\nArchitecture: {arch}\n"),
    )
    .context("writing the scratch debian/control")?;

    let package_root = debian.join(NAME);
    let mut written = lay_out(&package_root.join("usr"), &binary, None)?;
    written.extend(lay_out_settings_scripts(&package_root.join("usr"))?);
    written.extend(deb_doc_files(&package_root.join("usr"), &version)?);
    let installed_binary = package_root.join("usr/bin").join(NAME);

    // Debian ships stripped binaries. The line tables the release profile
    // carries stay on the build machine's unstripped copy, which is what a
    // crash log's module+offset frames are resolved against; in the
    // package they were a couple hundred megabytes the loader never pages
    // in. The check below then runs the stripped copy, the one that ships.
    let status = Command::new("strip")
        .arg("--strip-unneeded")
        .arg(&installed_binary)
        .status()
        .context("spawning strip")?;
    if !status.success() {
        bail!("strip exited with {status}");
    }
    check_installed(&installed_binary, &version)?;

    // The staging directories inherit the building user's umask; dpkg-deb
    // archives whatever it sees, and Debian directories are 0755.
    normalize_dir_modes(&package_root)?;

    // The C dependencies are read off the binary; the Tcl/Tk ones are the
    // settings window's, stated by name because no ELF names them.
    let depends = format!("{}, tcl9.0, tk9.0", shlibdeps(scratch.path(), &installed_binary)?);

    // Installed-Size is in KiB, and is the size of the installed files, which
    // for this package is robco-term plus two small data files plus the
    // robco-settings sources.
    let installed_size: u64 = written
        .iter()
        .filter_map(|path| std::fs::metadata(path).ok())
        .map(|m| m.len())
        .sum::<u64>()
        .div_ceil(1024);

    let control_dir = package_root.join("DEBIAN");
    std::fs::create_dir_all(&control_dir)?;
    std::fs::write(
        control_dir.join("control"),
        control(&version, &arch, &depends, installed_size),
    )
    .context("writing DEBIAN/control")?;

    std::fs::create_dir_all(&args.out_dir)
        .with_context(|| format!("creating {}", args.out_dir.display()))?;
    let out_dir = std::fs::canonicalize(&args.out_dir)?;
    let deb_path = out_dir.join(format!("{NAME}_{version}_{arch}.deb"));

    // --root-owner-group is what makes this sudo-free: without it dpkg-deb
    // stamps the building user's uid/gid into the archive and needs fakeroot
    // or root to write 0:0.
    let status = Command::new("dpkg-deb")
        .arg("--build")
        .arg("--root-owner-group")
        .arg(&package_root)
        .arg(&deb_path)
        .status()
        .context("spawning dpkg-deb")?;
    if !status.success() {
        bail!("dpkg-deb exited with {status}");
    }

    println!("wrote {}", deb_path.display());
    println!("  Depends: {depends}");
    Ok(())
}

/// The `Depends` line, from `dpkg-shlibdeps` reading the built binary.
fn shlibdeps(cwd: &Path, binary: &Path) -> Result<String> {
    let output = Command::new("dpkg-shlibdeps")
        .current_dir(cwd)
        .arg("-O")
        .arg("--ignore-missing-info")
        .arg(binary)
        .output()
        .context("spawning dpkg-shlibdeps")?;
    if !output.status.success() {
        bail!(
            "dpkg-shlibdeps exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let text = String::from_utf8_lossy(&output.stdout);
    text.lines()
        .find_map(|line| line.strip_prefix("shlibs:Depends="))
        .map(|deps| deps.trim().to_string())
        .filter(|deps| !deps.is_empty())
        .context("dpkg-shlibdeps produced no shlibs:Depends line")
}

/// The package's own control file.
///
/// `Provides: x-terminal-emulator` is the Debian tag for "this is a terminal";
/// the matching `update-alternatives` registration wants maintainer scripts,
/// which a package this simple does not carry, so the tag is claimed and the
/// alternative is not.
fn control(version: &str, arch: &str, depends: &str, installed_size: u64) -> String {
    format!(
        "Package: {NAME}\n\
         Version: {version}\n\
         Architecture: {arch}\n\
         Section: x11\n\
         Priority: optional\n\
         Installed-Size: {installed_size}\n\
         Maintainer: {}\n\
         Depends: {depends}\n\
         Provides: x-terminal-emulator\n\
         Description: terminal emulator which mimics old screens\n\
        \x20RobCo Terminal is a terminal emulator which mimics the look and feel\n\
        \x20of the old cathode tube screens. It has been designed to be eye-candy,\n\
        \x20customizable, and reasonably lightweight.\n",
        maintainer()
    )
}

/// `Maintainer` is a required Debian field. The person comes from
/// `DEBFULLNAME`/`DEBEMAIL`, the same environment `dch` and the other
/// Debian tools read, so no name lives in this source; without them the
/// placeholder stands, and lintian's `bogus-mail-host` will say so.
fn maintainer() -> String {
    match (std::env::var("DEBFULLNAME"), std::env::var("DEBEMAIL")) {
        (Ok(name), Ok(email)) if !name.is_empty() && !email.is_empty() => {
            format!("{name} <{email}>")
        }
        _ => "RobCo Terminal maintainers <robco-term@localhost>".to_string(),
    }
}

/// `command -v`, without a shell.
fn which(tool: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|dir| dir.join(tool))
        .find(|candidate| candidate.is_file())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The version is readable, and it is the workspace's rather than
    /// xtask's own: the mistake `CARGO_PKG_VERSION` would have made.
    #[test]
    fn version_comes_from_the_workspace_manifest() {
        let version = version().expect("workspace version");
        assert!(
            version.split('.').count() >= 2,
            "not a version: {version:?}"
        );
        let doc: toml_edit::DocumentMut = WORKSPACE_MANIFEST.parse().unwrap();
        assert!(
            doc.get("workspace").is_some(),
            "the parsed manifest is not the workspace one"
        );
    }

    /// The layout is the XDG one, and it is exactly three files with no
    /// settings binary given: a change to either is a packaging decision,
    /// not an accident.
    #[test]
    fn lay_out_writes_the_xdg_file_set() {
        let root = tempfile::tempdir().unwrap();
        let fake_binary = root.path().join("fake-binary");
        std::fs::write(&fake_binary, b"#!/bin/true\n").unwrap();

        let prefix = root.path().join("prefix");
        let written = lay_out(&prefix, &fake_binary, None).unwrap();

        let relative: Vec<String> = written
            .iter()
            .map(|p| p.strip_prefix(&prefix).unwrap().display().to_string())
            .collect();
        assert_eq!(
            relative,
            vec![
                "bin/robco-term".to_string(),
                "share/applications/robco-term.desktop".to_string(),
                "share/icons/hicolor/256x256/apps/robco-term.png".to_string(),
            ]
        );
        for path in &written {
            assert!(path.is_file(), "{} was not written", path.display());
        }
    }

    /// Given a settings binary, it lands as a fourth file, `bin/robco-settings`,
    /// appended after the three XDG files rather than displacing any of them.
    #[test]
    fn lay_out_adds_the_settings_binary_when_given() {
        let root = tempfile::tempdir().unwrap();
        let fake_binary = root.path().join("fake-binary");
        std::fs::write(&fake_binary, b"#!/bin/true\n").unwrap();
        let fake_settings = root.path().join("fake-settings");
        std::fs::write(&fake_settings, b"#!/bin/true\n").unwrap();

        let prefix = root.path().join("prefix");
        let written = lay_out(&prefix, &fake_binary, Some(&fake_settings)).unwrap();

        let relative: Vec<String> = written
            .iter()
            .map(|p| p.strip_prefix(&prefix).unwrap().display().to_string())
            .collect();
        assert_eq!(
            relative,
            vec![
                "bin/robco-term".to_string(),
                "share/applications/robco-term.desktop".to_string(),
                "share/icons/hicolor/256x256/apps/robco-term.png".to_string(),
                "bin/robco-settings".to_string(),
            ]
        );
        for path in &written {
            assert!(path.is_file(), "{} was not written", path.display());
        }
    }

    /// The binary is installed executable and the data files are not: a
    /// desktop entry with the execute bit set is a lint failure downstream.
    /// The settings binary, when given, is executable too.
    #[cfg(unix)]
    #[test]
    fn lay_out_sets_the_modes_a_package_needs() {
        use std::os::unix::fs::PermissionsExt;
        let root = tempfile::tempdir().unwrap();
        let fake_binary = root.path().join("fake-binary");
        std::fs::write(&fake_binary, b"#!/bin/true\n").unwrap();
        let fake_settings = root.path().join("fake-settings");
        std::fs::write(&fake_settings, b"#!/bin/true\n").unwrap();
        let prefix = root.path().join("prefix");
        let written = lay_out(&prefix, &fake_binary, Some(&fake_settings)).unwrap();

        let mode = |p: &Path| std::fs::metadata(p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode(&written[0]), 0o755, "the binary");
        assert_eq!(mode(&written[3]), 0o755, "the settings binary");
        for data in &written[1..3] {
            assert_eq!(mode(data), 0o644, "{}", data.display());
        }
    }

    /// The desktop entry the installer embeds is the identity the rest of the
    /// system keys off: the file's name, its `Icon=`, and the WM_CLASS the
    /// window presents are all this one string.
    #[test]
    fn the_desktop_entry_names_the_identity() {
        assert!(DESKTOP_ENTRY.contains(&format!("Exec={NAME}")));
        assert!(DESKTOP_ENTRY.contains(&format!("Icon={NAME}")));
        assert!(DESKTOP_ENTRY.contains(&format!("StartupWMClass={NAME}")));
        assert!(DESKTOP_ENTRY.contains("Type=Application"));
    }

    /// The icons are real PNGs, checked by their signature rather than
    /// trusted: an empty or truncated placeholder installs just as quietly as
    /// a good one.
    #[test]
    fn the_icons_are_pngs() {
        for (size, bytes) in ICONS {
            assert!(
                bytes.starts_with(b"\x89PNG\r\n\x1a\n"),
                "the {size}px icon is not a PNG"
            );
        }
    }

    /// The built path is read out of cargo's own report: the `null`
    /// executables of library artifacts are skipped, and the real one wins
    /// wherever cargo decided to put it.
    #[test]
    fn the_executable_is_read_from_cargos_report() {
        let stdout = concat!(
            r#"{"reason":"compiler-artifact","target":{"name":"robco-app","kind":["lib"]},"executable":null}"#,
            "\n",
            r#"{"reason":"compiler-artifact","target":{"name":"robco-term","kind":["bin"]},"executable":"/somewhere/else/release/robco-term"}"#,
            "\n",
            r#"{"reason":"build-finished","success":true}"#,
            "\n",
        );
        assert_eq!(
            executable_from_cargo_messages(stdout),
            Some(PathBuf::from("/somewhere/else/release/robco-term"))
        );
        assert_eq!(executable_from_cargo_messages(""), None);
    }

    /// DESTDIR re-roots the prefix; without one the prefix is the root.
    #[test]
    fn destdir_reroots_the_prefix() {
        assert_eq!(
            staged_root(Path::new("/usr"), Some(Path::new("/staging"))),
            PathBuf::from("/staging/usr")
        );
        assert_eq!(
            staged_root(Path::new("/opt/robco"), None),
            PathBuf::from("/opt/robco")
        );
    }

    /// The artifact stem carries the version and the architecture, because
    /// this build is native per platform rather than cross-compiled.
    #[test]
    fn the_artifact_stem_names_version_and_arch() {
        let stem = artifact_stem("9.9.9");
        assert!(stem.starts_with("robco-term-9.9.9-linux-"));
        assert!(stem.ends_with(std::env::consts::ARCH));
    }

    /// The installed launcher must point at the package's share directory,
    /// wherever the checkout kept its sources, and a launcher whose ROOT
    /// line vanished is a refusal, not a silent pass-through.
    #[test]
    fn the_deb_launcher_gets_its_root_pointed_at_share() {
        let launcher = "#!/usr/bin/env tclsh9.0\nset ROOT [file dirname [file normalize [info script]]]\nsource [file join $ROOT lib toml.tcl]\n";
        let patched = point_root_at(launcher, "/usr/share/robco-term/settings").unwrap();
        assert!(patched.contains("set ROOT /usr/share/robco-term/settings\n"));
        assert!(!patched.contains("info script"), "{patched}");
        assert!(point_root_at("#!/usr/bin/env tclsh9.0\n", "/usr/share/x").is_err());
    }

    /// The control file is a single RFC822 stanza with the fields dpkg
    /// requires, and its Description continuation lines are space-prefixed.
    #[test]
    fn the_control_stanza_has_the_required_fields() {
        let text = control("1.2.3", "amd64", "libc6 (>= 2.39)", 42);
        for field in [
            "Package: robco-term",
            "Version: 1.2.3",
            "Architecture: amd64",
            "Installed-Size: 42",
            "Depends: libc6 (>= 2.39)",
            "Maintainer: ",
            "Description: ",
        ] {
            assert!(
                text.contains(field),
                "control is missing {field:?}:\n{text}"
            );
        }
        let description = text.split("Description: ").nth(1).unwrap();
        for line in description.lines().skip(1).filter(|l| !l.is_empty()) {
            assert!(
                line.starts_with(' '),
                "continuation line is not folded: {line:?}"
            );
        }
    }

    /// The timestamp `dist` stamps into the archive is a real commit time
    /// off git, not `0` from a parse that silently failed.
    #[test]
    fn released_commit_timestamp_reads_a_real_git_time() {
        let ts = released_commit_timestamp().expect("HEAD's commit timestamp");
        // Sanity floor: any commit in this project's history postdates its
        // repository's creation, so this only fails if the parse returned
        // garbage (or `0`) rather than an actual `git log` timestamp.
        assert!(ts > 1_700_000_000, "implausible commit timestamp: {ts}");
    }

    /// The whole point of stamping a fixed `--mtime`: two archiving runs
    /// over staging directories whose files really do carry different mtimes
    /// (the normal case -- each `dist` invocation re-lays-out into a fresh
    /// tempdir) still produce byte-identical tarballs, because the archive
    /// records the given `mtime` rather than whatever the filesystem has.
    #[test]
    fn archive_is_reproducible_across_two_runs() {
        let root = tempfile::tempdir().unwrap();
        let fake_binary = root.path().join("fake-binary");
        std::fs::write(&fake_binary, b"pretend binary bytes\n").unwrap();
        let stem = "robco-term-9.9.9-linux-test";
        let fixed_mtime = 1_700_000_000;

        let staging_a = root.path().join("staging-a");
        lay_out(&staging_a.join(stem), &fake_binary, None).unwrap();
        let out_a = root.path().join("out-a");
        let tarball_a = archive(&staging_a, stem, &out_a, fixed_mtime).unwrap();

        // A real gap, so the second staging directory's files carry mtimes
        // the first's genuinely do not -- what actually distinguishes two
        // separate `dist` runs -- rather than this test passing because both
        // runs happened in the same filesystem-timestamp tick regardless of
        // the flag under test.
        std::thread::sleep(std::time::Duration::from_millis(1100));

        let staging_b = root.path().join("staging-b");
        lay_out(&staging_b.join(stem), &fake_binary, None).unwrap();
        let out_b = root.path().join("out-b");
        let tarball_b = archive(&staging_b, stem, &out_b, fixed_mtime).unwrap();

        let bytes_a = std::fs::read(&tarball_a).unwrap();
        let bytes_b = std::fs::read(&tarball_b).unwrap();
        assert_eq!(
            bytes_a, bytes_b,
            "two dist archives at the same --mtime were not byte-identical"
        );
    }
}
