//! The bank's furniture, composited over the presented frame.
//!
//! Chassis chrome lives *outside* the CRT chain. The bezel is the one
//! exception, and rides in the chain's frame slot because it hugs the curved
//! glass it is set into. The casting to the left of the well is drawn by
//! [`crate::chrome`], natively, straight onto the swapchain. What is left
//! here is the furniture that stands on that casting: the shell's plate and
//! one channel display per row, each still a librashader pass.
//!
//! # Why it is drawn offscreen and then blitted
//!
//! `chassis` owns the shaders and draws nothing itself, so this is the host's
//! mount, the same shape `crt::Chain` is. But a librashader chain's last pass
//! begins its render pass with `LoadOp::Clear` over the whole attachment
//! (`librashader-runtime-wgpu`'s `graphics_pipeline::begin_rendering`), and it
//! sets its scissor afterwards, so pointing a second chain straight at the
//! swapchain view would wipe the frame the first one just drew there. Each
//! piece is therefore rendered into a scratch texture of its own and blitted
//! into a column texture, over what is already there; the column texture
//! accumulates the whole bank and only then goes on the frame, blended over
//! the casting the chrome pass laid down. Treating each row as a piece
//! composited into the shared column texture gives clipping for free: a
//! strip's spill margin reaches past the column's edges and is cut there by
//! the scissor rather than landing on the glass.
//!
//! The column texture is cleared to transparent at the head of every frame,
//! so what it carries is exactly the furniture, premultiplied, and the blend
//! that puts it on the frame is an ordinary source-over.
//!
//! The pieces' rectangles are logical pixels and this texture is physical, so
//! the mount scales them on the way in ([`crate::chrome::scale_rect`]). What
//! it does *not* scale is the uniforms: `sizePx`, `gridSize` and the glyph
//! rectangle are all measured in logical coordinates, so a 2.5 px bevel is two
//! and a half logical pixels drawn across five device ones on a scaled
//! display. That is why nothing here multiplies a uniform by the ratio.

use std::path::{Path, PathBuf};

use chassis::furniture::{Pass, Piece, Raster};
use librashader::presets::ShaderFeatures;
use librashader::runtime::wgpu::{FilterChain, FilterChainOptions, WgpuOutputView};
use librashader::runtime::{FilterChainParameters, Size, Viewport};

/// The three furniture passes, each `shaders = 1` over its own body: the same
/// preset text `chassis/shaders/*/` ships beside each `.slang`, written out
/// here because a shipped binary carries its shaders rather than looking for a
/// source tree ([`chassis::shaders`]'s own reasoning).
///
/// `filter_linear0 = false` is not decoration on any of the three. The lamp
/// grid reads exactly one texel per cell and a filtered sample would light
/// lamps between two of them; the tape's `punched()` dilates a nearest sample
/// by hand and the kit's oracle test is written against that.
const FURNITURE: &[(Pass, &str, &str, &str)] = &[
    (
        Pass::Plate,
        "plate_metal.slang",
        "chassis_plate.slangp",
        chassis::shaders::PLATE_METAL_SLANG,
    ),
    (
        Pass::LedMatrix,
        "led_matrix.slang",
        "chassis_led.slangp",
        chassis::shaders::LED_MATRIX_SLANG,
    ),
    (
        Pass::TapeLabel,
        "tape_label.slang",
        "chassis_tape.slangp",
        chassis::shaders::TAPE_LABEL_SLANG,
    ),
];

fn preset_text(body: &str) -> String {
    format!(
        "# Generated by robco-term. Bank furniture, mounted outside the CRT\n\
         # chain, composited over the finished glass. Body from `chassis::shaders`.\n\
         shaders = 1\n\
         \n\
         shader0 = {body}\n\
         scale_type0 = source\n\
         scale0 = 1.0\n\
         filter_linear0 = false\n\
         wrap_mode0 = clamp_to_edge\n"
    )
}

/// Write a shader body only when what is on disk is not already it, so a
/// second window does not rewrite the file a first one is reading.
fn write_body(path: &Path, wanted: &str) -> std::io::Result<()> {
    if std::fs::read(path)
        .map(|got| got != wanted.as_bytes())
        .unwrap_or(true)
    {
        std::fs::write(path, wanted)?;
    }
    Ok(())
}

/// The include files any of the chassis shader bodies may pull in, written
/// beside them under their own names.
fn write_includes(dir: &Path) -> std::io::Result<()> {
    for (file, source) in chassis::shaders::INCLUDES {
        write_body(&dir.join(file), source)?;
    }
    Ok(())
}

/// Write one furniture pass's preset and shader body into `dir`;
/// returns the preset's path.
pub fn materialize_furniture(dir: &Path, pass: Pass) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(dir)?;
    write_includes(dir)?;
    let (_, body, slangp, source) = FURNITURE
        .iter()
        .find(|(p, ..)| *p == pass)
        .expect("every Pass has a body");
    write_body(&dir.join(body), source)?;
    let preset = dir.join(slangp);
    std::fs::write(&preset, preset_text(body))?;
    Ok(preset)
}

/// The mounted furniture: the texture the pieces are assembled in, the
/// chains that draw them, and the blit that puts that texture on the frame.
pub struct Column {
    target: wgpu::Texture,
    view: wgpu::TextureView,
    /// The column's own size in physical pixels, so a resize rebuilds the
    /// texture and nothing else.
    size: (u32, u32),
    format: wgpu::TextureFormat,
    blit: Blit,
    /// One chain per piece, loaded on first use.
    ///
    /// Per piece, and not per *pass*, for a reason worth stating: librashader
    /// pushes a chain's parameters into its uniform buffer with
    /// `queue.write_buffer` (`librashader-runtime-wgpu`'s `buffer.rs:34`), and
    /// a queue write lands before every command in the submission it precedes.
    /// Nineteen strips recorded into one encoder through one chain would
    /// therefore all render with the *last* strip's uniforms: the lit window
    /// would come out dark, and no test that renders a single piece could ever
    /// see it.
    ///
    /// What *is* shared safely is a chain whose uniform buffer would be
    /// written identically, which is why the key is [`ChainKey`] rather than
    /// the piece's index: the buffer holds the pass's own parameters plus the
    /// built-in semantics librashader derives from the two sizes, and nothing
    /// else. Everything per-piece that is not in that buffer (the source
    /// texture above all) rides in a bind group librashader builds inside
    /// each `frame()` call (`filter_pass.rs:162`), so two strips carrying
    /// different titles at the same size and the same lit/dim state share one
    /// chain and still draw their own glyphs. On the shipped bank that turns
    /// twenty compiles into three.
    chains: Vec<ChainEntry>,
    /// Frames drawn, for retiring a chain no piece has asked for in a while.
    frames: u64,
    /// Where the furniture presets were written, for that late load.
    dir: PathBuf,
    /// One scratch per piece, held across frames: the plan is the same list
    /// of rectangles frame after frame, so after the first one this allocates
    /// nothing. `None` is a piece whose rectangle fell entirely off the
    /// column and was never given one.
    slots: Vec<Option<Slot>>,
}

/// Everything that decides what librashader writes into a chain's uniform
/// buffer: the pass, its parameters, and the two sizes the built-in semantics
/// (`OutputSize`, `SourceSize`, `OriginalSize`) are derived from.
///
/// Two pieces with equal keys can be recorded through one chain in one
/// encoder; two with different keys cannot. See [`Column::chains`].
#[derive(PartialEq)]
struct ChainKey {
    pass: Pass,
    size: (u32, u32),
    source_size: (u32, u32),
    params: Vec<(&'static str, f32)>,
}

struct ChainEntry {
    key: ChainKey,
    chain: FilterChain,
    /// The frame this entry was last asked for, so a profile change does not
    /// leave its old chains behind for the life of the window.
    used: u64,
}

/// One piece, prepared and ready to record: which piece, where it goes on the
/// column in physical pixels, and which of [`Column::chains`] draws it.
///
/// The two halves of `draw_furniture` exist because the borrows do not
/// overlap, and this is what passes between them.
struct Recording {
    piece: usize,
    dest: (i32, i32, u32, u32),
    /// Which of [`Column::chains`] draws it, or `None` for a painted piece,
    /// whose picture is already in its slot's source texture.
    chain: Option<usize>,
}

/// How long an unused chain is kept. At the shipped 20 Hz effects clock that
/// is about half a minute: long enough that flipping a setting back and
/// forth costs no recompile, short enough that a chain nothing wants is not
/// held for the life of the window.
const CHAIN_TTL_FRAMES: u64 = 600;

/// The scratch one piece is rendered in before it is blitted onto the column.
///
/// A [`Pass::Painted`] piece has no pass to render, so it has no scratch
/// either: its picture is rasterised on the CPU straight into the source
/// texture and blitted from there. `target`/`view`/`bind` are therefore
/// `None` for one, and `source_bind` is `Some`. The two are never both set,
/// and which one it is says which kind of piece the slot belongs to.
struct Slot {
    size: (u32, u32),
    /// Held, not read: the view below is what everything uses, and a view
    /// whose texture has been dropped is a validation error at draw time.
    #[allow(dead_code)]
    target: Option<wgpu::Texture>,
    view: Option<wgpu::TextureView>,
    bind: Option<wgpu::BindGroup>,
    /// The glyph raster this piece's pass samples, and its size, so a strip
    /// whose text has not changed shape reuses the texture. For a painted
    /// piece this is the picture itself, at the destination's own size.
    source: wgpu::Texture,
    source_size: (u32, u32),
    /// A bind group over [`Slot::source`], for a painted piece: what the blit
    /// copies onto the column when there is no pass in between.
    source_bind: Option<wgpu::BindGroup>,
    /// The description the picture in `source` was rasterised from, so a bank
    /// standing still rasterises nothing. `None` for a shaded piece.
    ///
    /// This is the whole reason [`chassis::paint::Painting`] is a value with
    /// an equality rather than a closure or an image: the plan is rebuilt
    /// every frame from the channel model, and on all but the frames where
    /// something actually changed the new description is equal to the old one
    /// and the twelve numerals are not re-struck.
    painting: Option<chassis::paint::Painting>,
    /// The destination rectangle, in this slot's own uniform buffer.
    dest: wgpu::Buffer,
}

impl Column {
    /// Prepare the furniture's mount for a device. `format` is the
    /// swapchain's, so the textures the blit samples and the views it writes
    /// are the same format and librashader compiles each pass against it once.
    pub fn new(
        device: &wgpu::Device,
        _queue: &wgpu::Queue,
        dir: &Path,
        format: wgpu::TextureFormat,
    ) -> Option<Self> {
        let size = (1, 1);
        let target = make_target(device, format, size);
        let view = target.create_view(&wgpu::TextureViewDescriptor::default());
        Some(Self {
            target,
            view,
            size,
            format,
            blit: Blit::new(device, format),
            chains: Vec::new(),
            frames: 0,
            dir: dir.to_path_buf(),
            slots: Vec::new(),
        })
    }

    /// The chain for a piece, as an index into [`Column::chains`]: an existing
    /// one whose uniform buffer this piece would write identically, or a newly
    /// compiled one.
    ///
    /// An index rather than a reference so the caller can hold a slot at the
    /// same time. `None` is a body that would not compile, which says so once
    /// per frame (the loud kind of quiet).
    fn chain_for(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        key: ChainKey,
    ) -> Option<usize> {
        if let Some(i) = self.chains.iter().position(|e| e.key == key) {
            self.chains[i].used = self.frames;
            return Some(i);
        }
        let pass = key.pass;
        let preset = match materialize_furniture(&self.dir, pass) {
            Ok(path) => path,
            Err(e) => {
                log::error!(
                    "could not write the {pass:?} preset into {:?}: {e}",
                    self.dir
                );
                return None;
            }
        };
        let options = FilterChainOptions {
            force_no_mipmaps: false,
            enable_cache: false,
            adapter_info: None,
        };
        let started = std::time::Instant::now();
        match FilterChain::load_from_path(
            &preset,
            ShaderFeatures::NONE,
            device,
            queue,
            Some(&options),
        ) {
            Ok(chain) => {
                // One line per compile, because the count is what the first
                // frame's cost is spent on and it is not obvious from the
                // outside how few of these there should be.
                log::debug!(
                    "bank furniture: {pass:?} at {:?} over {:?} compiled in {:?}",
                    key.size,
                    key.source_size,
                    started.elapsed()
                );
                self.chains.push(ChainEntry {
                    key,
                    chain,
                    used: self.frames,
                });
                Some(self.chains.len() - 1)
            }
            Err(e) => {
                log::error!("could not load {pass:?} from {}: {e}", preset.display());
                None
            }
        }
    }

    /// Record the furniture into `output`.
    ///
    /// `column` is the bank's rectangle in physical pixels at the window's left
    /// edge, the same rectangle [`crate::chrome`] laid the casting into;
    /// `frame` is the window's own size, which is what the blit's destination
    /// rectangle is measured against. `scale_factor` is the window's device
    /// pixel ratio. `pieces` is `chassis::Cabinet::furniture`, whose
    /// rectangles are logical and are scaled by that ratio on the way in.
    ///
    /// A column of no width draws nothing, which is what a hidden chassis is:
    /// no bank rather than a bank of zero pixels.
    #[allow(clippy::too_many_arguments)]
    pub fn render(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        output: &wgpu::TextureView,
        column: (u32, u32),
        frame: (u32, u32),
        scale_factor: f64,
        pieces: &[Piece],
        frame_index: usize,
    ) {
        if column.0 == 0 || column.1 == 0 {
            return;
        }
        if self.size != column {
            self.target = make_target(device, self.format, column);
            self.view = self
                .target
                .create_view(&wgpu::TextureViewDescriptor::default());
            self.size = column;
            self.blit.rebind(device, &self.view);
        }

        // Transparent, every frame: what this texture carries is the
        // furniture alone, premultiplied, and the casting it stands on is
        // already on the frame this is about to be blended onto.
        encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            label: Some("bank furniture ground"),
            color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                view: &self.view,
                depth_slice: None,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color::TRANSPARENT),
                    store: wgpu::StoreOp::Store,
                },
            })],
            depth_stencil_attachment: None,
            timestamp_writes: None,
            occlusion_query_set: None,
            multiview_mask: None,
        });

        self.draw_furniture(device, queue, encoder, pieces, scale_factor, frame_index);
        self.blit.draw(queue, encoder, output, column, frame);
    }

    /// The plate and the strips, each through its own pass and into the column
    /// texture the casting is already on.
    ///
    /// Two passes over the plan, because the borrows do not overlap otherwise:
    /// the first prepares every piece's scratch and compiles whatever pass it
    /// needs, the second records. Nothing between them touches the GPU.
    fn draw_furniture(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        pieces: &[Piece],
        scale_factor: f64,
        frame_index: usize,
    ) {
        let column = self.size;
        self.frames += 1;
        self.slots.resize_with(pieces.len(), || None);

        let mut plan: Vec<Recording> = Vec::new();
        for (i, piece) in pieces.iter().enumerate() {
            let Some(dest) = crate::chrome::scale_rect(piece.rect, scale_factor, column)
            else {
                continue;
            };
            if let Some(painting) = piece.paint.as_ref() {
                self.ensure_painted_slot(device, queue, i, painting, dest, column, scale_factor);
                if self.slots[i].is_some() {
                    plan.push(Recording {
                        piece: i,
                        dest,
                        chain: None,
                    });
                }
                continue;
            }
            self.ensure_slot(device, queue, i, piece.source.as_ref(), dest, column);
            let Some(slot) = self.slots[i].as_ref() else {
                continue;
            };
            // The uploads go through the queue, which lands every one of them
            // before this encoder's commands run: a strip therefore needs a
            // texture of its own rather than sharing one with its neighbours,
            // and `ensure_slot` gives it one. The chains are shared only where
            // the uniform buffer would be written identically; see
            // [`Column::chains`].
            let key = ChainKey {
                pass: piece.pass,
                size: slot.size,
                source_size: slot.source_size,
                params: piece.params.clone(),
            };
            if let Some(raster) = piece.source.as_ref() {
                upload(queue, &slot.source, raster);
            }
            if let Some(chain) = self.chain_for(device, queue, key) {
                plan.push(Recording {
                    piece: i,
                    dest,
                    chain: Some(chain),
                });
            }
        }
        let Column {
            view,
            format,
            blit,
            chains,
            slots,
            ..
        } = self;
        for Recording {
            piece: i,
            dest,
            chain,
        } in plan
        {
            let Some(slot) = slots[i].as_ref() else {
                continue;
            };
            let Some(chain) = chain else {
                // Painted: the picture is already in the slot's source
                // texture, so there is nothing to render and the blit reads
                // it straight.
                if let Some(bind) = slot.source_bind.as_ref() {
                    blit.draw_over(encoder, view, bind, dest, column);
                }
                continue;
            };
            let (Some(slot_view), Some(slot_bind)) = (slot.view.as_ref(), slot.bind.as_ref())
            else {
                continue;
            };
            let chain = &mut chains[chain].chain;
            let sink = chain.parameters();
            for (name, value) in &pieces[i].params {
                sink.set_parameter_value(name, *value);
            }
            // Nothing in the three bodies reads `OutputSize`: the geometry
            // they draw is in the `sizePx`/`gridSize` uniforms the piece
            // carries, so the declared size is this scratch's own.
            let declared = Size::new(slot.size.0, slot.size.1);
            let viewport = Viewport {
                x: 0.0,
                y: 0.0,
                mvp: None,
                output: WgpuOutputView::new_from_raw(slot_view, declared, *format),
                size: declared,
            };
            if let Err(e) = chain.frame(&slot.source, &viewport, encoder, frame_index, None) {
                log::error!("could not record a {:?} piece: {e}", pieces[i].pass);
                continue;
            }
            blit.draw_over(encoder, view, slot_bind, dest, column);
        }

        // After the recording, never before it: `plan` holds indices into
        // this vector.
        let horizon = self.frames.saturating_sub(CHAIN_TTL_FRAMES);
        self.chains.retain(|e| e.used >= horizon);
    }

    /// The scratch for piece `i`, made or remade only when its shape changed.
    fn ensure_slot(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        i: usize,
        source: Option<&Raster>,
        dest: (i32, i32, u32, u32),
        column: (u32, u32),
    ) {
        let size = (dest.2, dest.3);
        let source_size = source
            .map(|r| (r.width.max(1), r.height.max(1)))
            .unwrap_or((1, 1));
        let keep = self.slots[i].as_ref().is_some_and(|s| {
            s.size == size && s.source_size == source_size && s.painting.is_none()
        });
        if !keep {
            let target = make_target(device, self.format, size);
            let view = target.create_view(&wgpu::TextureViewDescriptor::default());
            let dest_buf = self.blit.make_dest(device);
            self.slots[i] = Some(Slot {
                size,
                bind: Some(self.blit.make_bind(device, &view, &dest_buf)),
                target: Some(target),
                view: Some(view),
                source: make_source(device, source_size),
                source_size,
                source_bind: None,
                painting: None,
                dest: dest_buf,
            });
        }
        // Written every frame either way: a rectangle can move without its
        // shape changing, which is what a seam drag does to every strip at
        // once.
        if let Some(slot) = self.slots[i].as_ref() {
            Blit::write_dest(queue, &slot.dest, dest, column);
        }
    }

    /// The slot for a painted piece: a texture holding the picture itself, at
    /// the destination's own size in physical pixels.
    ///
    /// No scratch and no chain, because there is no pass. The rasterising is
    /// the expensive half and it happens only when the shape of the slot or
    /// the description changed: a bank nobody is touching pays nothing per
    /// frame beyond the blit.
    #[allow(clippy::too_many_arguments)]
    fn ensure_painted_slot(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        i: usize,
        painting: &chassis::paint::Painting,
        dest: (i32, i32, u32, u32),
        column: (u32, u32),
        scale_factor: f64,
    ) {
        let size = (dest.2.max(1), dest.3.max(1));
        // `source_bind.is_some()` is the kind test, and it is the mirror of
        // `ensure_slot`'s `painting.is_none()`: the two functions build
        // different slots into one vector, so each has to refuse the other's.
        // A shaded slot of the same geometry has no `source_bind` (only a
        // `bind` onto its scratch), and reusing one here left it that way
        // while the painting uploaded into it -- and `draw_furniture` blits a
        // painted piece through `source_bind` alone, so the piece stopped
        // drawing with nothing logged. `chassis.channel_indicator` flips a
        // strip between a shaded pass and a painted one at the same geometry,
        // which is the reachable way in.
        let fresh = !self.slots[i]
            .as_ref()
            .is_some_and(|s| s.size == size && s.source_size == size && s.source_bind.is_some());
        if fresh {
            let dest_buf = self.blit.make_dest(device);
            let source = make_source(device, size);
            let view = source.create_view(&wgpu::TextureViewDescriptor::default());
            self.slots[i] = Some(Slot {
                size,
                target: None,
                view: None,
                bind: None,
                source_bind: Some(self.blit.make_bind(device, &view, &dest_buf)),
                source,
                source_size: size,
                painting: None,
                dest: dest_buf,
            });
        }
        let Some(slot) = self.slots[i].as_mut() else {
            return;
        };
        if slot.painting.as_ref() != Some(painting) {
            let painted = chassis::paint::rasterize(painting, size, scale_factor);
            upload(
                queue,
                &slot.source,
                &Raster {
                    width: painted.width,
                    height: painted.height,
                    rgba: painted.rgba,
                },
            );
            slot.painting = Some(painting.clone());
        }
        Blit::write_dest(queue, &slot.dest, dest, column);
    }
}

/// The texture a display pass samples as `Source`: one texel per lamp for the
/// LED grid, one per raster pixel for the tape.
fn make_source(device: &wgpu::Device, size: (u32, u32)) -> wgpu::Texture {
    device.create_texture(&wgpu::TextureDescriptor {
        label: Some("bank furniture source"),
        size: wgpu::Extent3d {
            width: size.0.max(1),
            height: size.1.max(1),
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    })
}

fn upload(queue: &wgpu::Queue, texture: &wgpu::Texture, raster: &Raster) {
    let (w, h) = (raster.width.max(1), raster.height.max(1));
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        &raster.rgba,
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(w * 4),
            rows_per_image: Some(h),
        },
        wgpu::Extent3d {
            width: w,
            height: h,
            depth_or_array_layers: 1,
        },
    );
}

fn make_target(
    device: &wgpu::Device,
    format: wgpu::TextureFormat,
    size: (u32, u32),
) -> wgpu::Texture {
    device.create_texture(&wgpu::TextureDescriptor {
        label: Some("bank column"),
        size: wgpu::Extent3d {
            width: size.0.max(1),
            height: size.1.max(1),
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    })
}

/// The copy that puts the furniture on the frame without clearing it.
///
/// One triangle, nearest-sampled, source and destination the same size, into a
/// render pass whose load op is `Load`. That last word is the whole reason this
/// type exists rather than a second `Viewport` pointed at the swapchain.
/// It also carries the destination rectangle, which is the second reason it is
/// not a viewport: a piece of furniture is allowed to hang off the column
/// (`chassis::furniture`'s LED windows do, by design), and `set_viewport`
/// rejects a rectangle that leaves the attachment. The rectangle therefore
/// rides in a uniform the vertex stage places the quad with, and the scissor
/// (which *may* be clamped, to reproduce the column's own clip) cuts what
/// falls outside.
struct Blit {
    /// Straight copy, kept as the fallback where the target cannot blend.
    pipeline: wgpu::RenderPipeline,
    /// Premultiplied source-over, for furniture onto the column and for the
    /// finished column onto the casting under it. Both display
    /// passes and the plate emit premultiplied colour: `plate_metal` returns
    /// `color * coverage` with `coverage` in alpha, and `led_matrix`'s spill
    /// band returns `litColor * a` with the same `a`.
    ///
    /// `None` only where the target format cannot blend at all, which no
    /// swapchain is: a float32 target needs `FLOAT32_BLENDABLE` and a window's
    /// is `Bgra8Unorm`. A measurement rig that renders into a float target and
    /// has not asked for the feature falls back to the straight copy, and
    /// every rounded corner and every spill band in the readback is then a
    /// hard edge: loudly wrong rather than a validation panic at startup.
    over: Option<wgpu::RenderPipeline>,
    layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    bind_group: Option<wgpu::BindGroup>,
    /// The column's own destination buffer, for the one blit that is not a
    /// piece.
    dest: Option<wgpu::Buffer>,
}

const BLIT_WGSL: &str = r#"
struct Out {
    @builtin(position) position: vec4<f32>,
    @location(0) uv: vec2<f32>,
};

// The destination rectangle in the target's 0..1 space: where the source's
// (0,0) lands, and how much of the target one unit of source spans.
struct Dest {
    offset: vec2<f32>,
    scale: vec2<f32>,
};

@group(0) @binding(2) var<uniform> dest: Dest;

@vertex
fn vs(@builtin(vertex_index) index: u32) -> Out {
    // The usual oversized triangle: three vertices covering the destination
    // rectangle twice over, with uv 0..1 across the rectangle itself. The
    // scissor is what cuts the surplus, and it is also what clips a rectangle
    // that hangs off the target.
    let x = f32((index << 1u) & 2u);
    let y = f32(index & 2u);
    var out: Out;
    out.uv = vec2<f32>(x, y);
    let p = vec2<f32>(x, y) * dest.scale + dest.offset;
    out.position = vec4<f32>(p.x * 2.0 - 1.0, 1.0 - p.y * 2.0, 0.0, 1.0);
    return out;
}

@group(0) @binding(0) var source: texture_2d<f32>;
@group(0) @binding(1) var source_sampler: sampler;

@fragment
fn fs(input: Out) -> @location(0) vec4<f32> {
    return textureSample(source, source_sampler, input.uv);
}
"#;

impl Blit {
    fn new(device: &wgpu::Device, format: wgpu::TextureFormat) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("bank column blit"),
            source: wgpu::ShaderSource::Wgsl(BLIT_WGSL.into()),
        });
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("bank column blit"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: false },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::NonFiltering),
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("bank column blit"),
            bind_group_layouts: &[Some(&layout)],
            immediate_size: 0,
        });
        let make = |label: &str, blend: Option<wgpu::BlendState>| {
            device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                label: Some(label),
                layout: Some(&pipeline_layout),
                vertex: wgpu::VertexState {
                    module: &shader,
                    entry_point: Some("vs"),
                    compilation_options: Default::default(),
                    buffers: &[],
                },
                fragment: Some(wgpu::FragmentState {
                    module: &shader,
                    entry_point: Some("fs"),
                    compilation_options: Default::default(),
                    targets: &[Some(wgpu::ColorTargetState {
                        format,
                        blend,
                        write_mask: wgpu::ColorWrites::ALL,
                    })],
                }),
                primitive: wgpu::PrimitiveState::default(),
                depth_stencil: None,
                multisample: wgpu::MultisampleState::default(),
                multiview_mask: None,
                cache: None,
            })
        };
        let pipeline = make("bank column blit", None);
        let blendable = format
            .guaranteed_format_features(device.features())
            .flags
            .contains(wgpu::TextureFormatFeatureFlags::BLENDABLE);
        if !blendable {
            log::warn!(
                "{format:?} cannot blend on this device: the bank's furniture will \
                 composite as straight copies, so its bevels and spill will read hard"
            );
        }
        let over = blendable.then(|| {
            make(
                "bank furniture blit",
                Some(wgpu::BlendState {
                    // Premultiplied source-over: `src + dst * (1 - src.a)`.
                    color: wgpu::BlendComponent {
                        src_factor: wgpu::BlendFactor::One,
                        dst_factor: wgpu::BlendFactor::OneMinusSrcAlpha,
                        operation: wgpu::BlendOperation::Add,
                    },
                    alpha: wgpu::BlendComponent {
                        src_factor: wgpu::BlendFactor::One,
                        dst_factor: wgpu::BlendFactor::OneMinusSrcAlpha,
                        operation: wgpu::BlendOperation::Add,
                    },
                }),
            )
        });
        Self {
            pipeline,
            over,
            layout,
            // Nearest, because the column is copied at 1:1 and a filtered
            // sample of procedural metal at 1:1 is the same pixel with extra
            // steps, and because a filtering sampler would need
            // FLOAT32_FILTERABLE on a float target.
            sampler: device.create_sampler(&wgpu::SamplerDescriptor {
                label: Some("bank column blit"),
                mag_filter: wgpu::FilterMode::Nearest,
                min_filter: wgpu::FilterMode::Nearest,
                ..Default::default()
            }),
            bind_group: None,
            dest: None,
        }
    }

    /// A destination-rectangle buffer: four floats, one per piece.
    fn make_dest(&self, device: &wgpu::Device) -> wgpu::Buffer {
        device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("bank blit destination"),
            size: 16,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        })
    }

    /// `dest` in physical pixels of a `target`-sized attachment, as the offset
    /// and scale the vertex stage wants.
    fn write_dest(
        queue: &wgpu::Queue,
        buffer: &wgpu::Buffer,
        dest: (i32, i32, u32, u32),
        target_size: (u32, u32),
    ) {
        let (tw, th) = (
            f64::from(target_size.0.max(1)),
            f64::from(target_size.1.max(1)),
        );
        let data: [f32; 4] = [
            (f64::from(dest.0) / tw) as f32,
            (f64::from(dest.1) / th) as f32,
            (f64::from(dest.2) / tw) as f32,
            (f64::from(dest.3) / th) as f32,
        ];
        // The struct is `offset: vec2, scale: vec2`, so the four floats go in
        // the order x, y, w, h.
        let bytes = [data[0], data[1], data[2], data[3]].map(f32::to_ne_bytes);
        let mut flat = [0u8; 16];
        for (i, b) in bytes.iter().enumerate() {
            flat[i * 4..i * 4 + 4].copy_from_slice(b);
        }
        queue.write_buffer(buffer, 0, &flat);
    }

    fn make_bind(
        &self,
        device: &wgpu::Device,
        view: &wgpu::TextureView,
        dest: &wgpu::Buffer,
    ) -> wgpu::BindGroup {
        device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("bank blit"),
            layout: &self.layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(view),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Sampler(&self.sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: dest.as_entire_binding(),
                },
            ],
        })
    }

    /// Rebind the column's own blit after a resize of the column texture.
    fn rebind(&mut self, device: &wgpu::Device, view: &wgpu::TextureView) {
        let dest = self.make_dest(device);
        self.bind_group = Some(self.make_bind(device, view, &dest));
        self.dest = Some(dest);
    }

    /// The finished column onto the frame, at the window's left edge, over
    /// the casting the chrome pass laid there.
    ///
    /// `frame` is the *window's* size, not the column's, because that is what
    /// the destination rectangle is measured against; the window can grow
    /// without the bank moving, so this is written every frame rather than at
    /// rebind.
    fn draw(
        &self,
        queue: &wgpu::Queue,
        encoder: &mut wgpu::CommandEncoder,
        output: &wgpu::TextureView,
        column: (u32, u32),
        frame: (u32, u32),
    ) {
        let (Some(bind_group), Some(dest)) = (self.bind_group.as_ref(), self.dest.as_ref()) else {
            return;
        };
        let rect = (0, 0, column.0, column.1);
        Self::write_dest(queue, dest, rect, frame);
        self.record(
            encoder,
            output,
            bind_group,
            rect,
            frame,
            self.over.as_ref().unwrap_or(&self.pipeline),
            "bank column",
        );
    }

    /// One piece of furniture, blended onto the column.
    fn draw_over(
        &self,
        encoder: &mut wgpu::CommandEncoder,
        output: &wgpu::TextureView,
        bind_group: &wgpu::BindGroup,
        dest: (i32, i32, u32, u32),
        target_size: (u32, u32),
    ) {
        self.record(
            encoder,
            output,
            bind_group,
            dest,
            target_size,
            self.over.as_ref().unwrap_or(&self.pipeline),
            "bank furniture",
        );
    }

    #[allow(clippy::too_many_arguments)]
    fn record(
        &self,
        encoder: &mut wgpu::CommandEncoder,
        output: &wgpu::TextureView,
        bind_group: &wgpu::BindGroup,
        dest: (i32, i32, u32, u32),
        target_size: (u32, u32),
        pipeline: &wgpu::RenderPipeline,
        label: &str,
    ) {
        // The bank clips its children. Here that is the scissor, clamped to
        // the attachment, which is also what keeps `set_scissor_rect` from
        // rejecting a rectangle that hangs off.
        let x0 = dest.0.max(0) as u32;
        let y0 = dest.1.max(0) as u32;
        let x1 = (dest.0 + dest.2 as i32).max(0) as u32;
        let y1 = (dest.1 + dest.3 as i32).max(0) as u32;
        let (x1, y1) = (x1.min(target_size.0), y1.min(target_size.1));
        if x0 >= x1 || y0 >= y1 {
            return;
        }
        let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            label: Some(label),
            color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                view: output,
                depth_slice: None,
                resolve_target: None,
                ops: wgpu::Operations {
                    // Load, not Clear: the glass, or the casting, is already
                    // on this image.
                    load: wgpu::LoadOp::Load,
                    store: wgpu::StoreOp::Store,
                },
            })],
            depth_stencil_attachment: None,
            timestamp_writes: None,
            occlusion_query_set: None,
            multiview_mask: None,
        });
        pass.set_pipeline(pipeline);
        pass.set_bind_group(0, Some(bind_group), &[]);
        pass.set_scissor_rect(x0, y0, x1 - x0, y1 - y0);
        pass.draw(0..3, 0..1);
    }
}
