//! Built-in screen and chassis presets, in their list order. Each preset's
//! shape is exactly what the persisted screen/chassis object produces, so
//! each one maps directly onto [`crate::ScreenSettings`] /
//! [`crate::ChassisSettings`].
//!
//! A screen preset states only what it changes from the default screen
//! ("Default Amber", `ScreenSettings::default()`): moving a value in the
//! default moves it in every preset that does not restate it, deliberately.
//! A field a preset means to pin regardless of the default must be stated
//! in the preset.
//!
//! The built-in list also carries a `builtin: true` flag and, for chassis, a
//! `description` string. Neither is part of the persisted screen/chassis
//! object; they are UI-list metadata, so they are not reproduced here.

use crate::schema::{
    ChannelDisplay, ChannelIndicator, ChassisSettings, Rasterization, ScreenSettings,
    Shell,
};

/// The built-in screen presets, in `screensList` order. Index 0 is the
/// default screen itself, [`ScreenSettings::default`].
pub fn screen_presets() -> Vec<ScreenSettings> {
    vec![
        ScreenSettings::default(),
        ScreenSettings {
            name: "Monochrome Green".to_string(),
            font_color: "#0ccc68".to_string(),
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.3,
            bloom: 0.5,
            font_name: "DEPARTURE_MONO_SCALED".to_string(),
            screen_radius: 0.2,
            frame_color: "#d4d4d4".to_string(),
            frame_shininess: 0.1,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Deep Blue".to_string(),
            font_color: "#7fb4ff".to_string(),
            chroma_color: 1.0,
            screen_curvature: 0.4,
            ambient_light: 0.0,
            font_name: "BIGBLUE_TERMINAL_SCALED".to_string(),
            frame_color: "#ffffff".to_string(),
            frame_shininess: 0.9,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Commodore 64".to_string(),
            background_color: "#3b3b8f".to_string(),
            font_color: "#a9a7ff".to_string(),
            horizontal_sync: 0.0,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.5,
            glowing_line: 0.1,
            burn_in: 0.1,
            bloom: 0.4,
            rasterization: Rasterization::ScanlineRasterization,
            jitter: 0.0,
            brightness: 0.6,
            contrast: 0.7,
            ambient_light: 0.4,
            font_name: "COMMODORE_64_SCALED".to_string(),
            frame_size: 0.5,
            frame_color: "#999999".to_string(),
            frame_shininess: 0.0,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Commodore PET".to_string(),
            font_color: "#ffffff".to_string(),
            flickering: 0.2,
            horizontal_sync: 0.2,
            static_noise: 0.2,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.7,
            glowing_line: 0.3,
            burn_in: 0.4,
            bloom: 0.4,
            rasterization: Rasterization::ScanlineRasterization,
            jitter: 0.15,
            ambient_light: 0.0,
            font_name: "COMMODORE_PET_SCALED".to_string(),
            font_width: 1.25,
            margin: 0.2,
            frame_size: 0.5,
            screen_radius: 0.3,
            frame_color: "#000000".to_string(),
            frame_shininess: 0.6,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Apple ][".to_string(),
            background_color: "#001100".to_string(),
            font_color: "#4dff6b".to_string(),
            flickering: 0.2,
            horizontal_sync: 0.2,
            static_noise: 0.2,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.5,
            glowing_line: 0.3,
            bloom: 0.3,
            rasterization: Rasterization::ScanlineRasterization,
            ambient_light: 1.0,
            font_name: "APPLE_II_SCALED".to_string(),
            font_width: 1.25,
            margin: 0.0,
            frame_size: 0.2,
            screen_radius: 0.3,
            frame_color: "#ffffff".to_string(),
            frame_shininess: 0.8,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Atari 400".to_string(),
            background_color: "#0f1f5a".to_string(),
            font_color: "#8ed6ff".to_string(),
            horizontal_sync: 0.0,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.4,
            glowing_line: 0.1,
            burn_in: 0.2,
            bloom: 0.1,
            rasterization: Rasterization::ScanlineRasterization,
            jitter: 0.0,
            brightness: 0.6,
            contrast: 0.9,
            ambient_light: 0.1,
            font_name: "ATARI_400_SCALED".to_string(),
            margin: 0.2,
            frame_size: 0.4,
            screen_radius: 0.2,
            frame_color: "#cccccc".to_string(),
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "IBM VGA 8x16".to_string(),
            font_color: "#c0c0c0".to_string(),
            horizontal_sync: 0.0,
            static_noise: 0.0,
            chroma_color: 0.5,
            saturation_color: 0.0,
            screen_curvature: 0.3,
            glowing_line: 0.1,
            burn_in: 0.1,
            bloom: 0.2,
            rasterization: Rasterization::ScanlineRasterization,
            jitter: 0.0,
            rgb_shift: 0.1,
            brightness: 0.6,
            contrast: 1.0,
            ambient_light: 0.2,
            font_name: "IBM_VGA_8x16".to_string(),
            margin: 0.2,
            frame_color: "#ffffff".to_string(),
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "IBM 3278 Reborn".to_string(),
            font_color: "#3cff7a".to_string(),
            flickering: 0.0,
            horizontal_sync: 0.0,
            static_noise: 0.0,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.0,
            glowing_line: 0.0,
            burn_in: 0.5,
            bloom: 0.2,
            rasterization: Rasterization::ModernRasterization,
            jitter: 0.0,
            ambient_light: 0.2,
            font_name: "IBM_3278".to_string(),
            margin: 0.1,
            frame_size: 0.0,
            screen_radius: 0.0,
            frame_color: "#ffffff".to_string(),
            frame_shininess: 0.2,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Neon Cyan".to_string(),
            background_color: "#001018".to_string(),
            font_color: "#52f7ff".to_string(),
            horizontal_sync: 0.0,
            chroma_color: 1.0,
            saturation_color: 0.6,
            screen_curvature: 0.0,
            burn_in: 0.1,
            rasterization: Rasterization::ModernRasterization,
            jitter: 0.1,
            brightness: 0.6,
            contrast: 0.9,
            ambient_light: 0.1,
            window_opacity: 0.8,
            font_name: "IOSEVKA".to_string(),
            margin: 0.1,
            frame_size: 0.0,
            screen_radius: 0.0,
            frame_color: "#c3c3c3".to_string(),
            frame_shininess: 0.2,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Ghost Terminal".to_string(),
            background_color: "#0b1014".to_string(),
            font_color: "#a6b3c0".to_string(),
            flickering: 0.0,
            horizontal_sync: 0.0,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.0,
            glowing_line: 0.1,
            burn_in: 0.2,
            bloom: 0.3,
            rasterization: Rasterization::ModernRasterization,
            jitter: 0.0,
            brightness: 0.6,
            contrast: 0.5,
            window_opacity: 0.7,
            font_name: "JETBRAINS_MONO".to_string(),
            margin: 0.1,
            frame_size: 0.0,
            screen_radius: 0.0,
            frame_color: "#a7a7a7".to_string(),
            frame_shininess: 0.2,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Plasma".to_string(),
            background_color: "#070014".to_string(),
            font_color: "#ff9bd6".to_string(),
            horizontal_sync: 0.0,
            chroma_color: 1.0,
            saturation_color: 0.8,
            screen_curvature: 0.0,
            burn_in: 0.1,
            bloom: 0.7,
            rasterization: Rasterization::ModernRasterization,
            jitter: 0.1,
            rgb_shift: 0.1,
            brightness: 0.6,
            ambient_light: 0.1,
            font_name: "FIRA_CODE".to_string(),
            margin: 0.1,
            frame_size: 0.0,
            screen_radius: 0.0,
            frame_color: "#d0d0d0".to_string(),
            frame_shininess: 0.2,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "Boring".to_string(),
            font_color: "#ffffff".to_string(),
            flickering: 0.0,
            horizontal_sync: 0.0,
            static_noise: 0.0,
            chroma_color: 1.0,
            saturation_color: 0.0,
            screen_curvature: 0.0,
            glowing_line: 0.1,
            burn_in: 0.05,
            bloom: 0.5,
            rasterization: Rasterization::ModernRasterization,
            jitter: 0.0,
            ambient_light: 0.1,
            font_name: "JETBRAINS_MONO".to_string(),
            margin: 0.0,
            frame_size: 0.0,
            screen_radius: 0.0,
            frame_color: "#c0c0c0".to_string(),
            frame_shininess: 0.2,
            ..ScreenSettings::default()
        },
        ScreenSettings {
            name: "E-Ink".to_string(),
            background_color: "#f2f2ec".to_string(),
            font_color: "#101010".to_string(),
            flickering: 0.0,
            horizontal_sync: 0.0,
            static_noise: 0.0,
            chroma_color: 0.0,
            saturation_color: 0.0,
            screen_curvature: 0.0,
            glowing_line: 0.0,
            burn_in: 0.6,
            bloom: 0.0,
            rasterization: Rasterization::ModernRasterization,
            jitter: 0.0,
            brightness: 1.0,
            contrast: 0.5,
            ambient_light: 0.6,
            font_name: "HACK".to_string(),
            margin: 0.1,
            frame_size: 0.0,
            screen_radius: 0.0,
            frame_color: "#cdcdcd".to_string(),
            frame_shininess: 0.2,
            ..ScreenSettings::default()
        },
    ]
}

pub fn chassis_presets() -> Vec<ChassisSettings> {
    vec![
        ChassisSettings {
            name: "Annunciator".to_string(),
            shell: Shell::Annunciator,
            channel_indicator: ChannelIndicator::Glow,
            channel_display: ChannelDisplay::Led,
            frame_size: 0.45,
            screen_radius: 0.44,
            frame_color: "#001735".to_string(),
            frame_shininess: 0.3,
        },
        ChassisSettings {
            name: "Slide Rule".to_string(),
            shell: Shell::SlideRule,
            channel_indicator: ChannelIndicator::Pointer,
            channel_display: ChannelDisplay::Led,
            frame_size: 0.7,
            screen_radius: 1.0,
            frame_color: "#a77d37".to_string(),
            frame_shininess: 0.15,
        },
        ChassisSettings {
            name: "Switchboard".to_string(),
            shell: Shell::Switchboard,
            channel_indicator: ChannelIndicator::Switch,
            channel_display: ChannelDisplay::Tape,
            frame_size: 0.2,
            screen_radius: 0.7,
            frame_color: "#461725".to_string(),
            frame_shininess: 0.2,
        },
    ]
}
